### ISSUE TITLE
npm package doesn't have lib folder

### ISSUE THREAD

**Issue by cmpxchg16b** [atlantishealthcare/swagger-model-validator#101]
Latest release is corrupted on npm registry and doesn't have lib & test folders:
https://registry.npmjs.org/swagger-model-validator/-/swagger-model-validator-3.0.2.tgz
3.0.1 has only lib folder, github releases are fine

**Comment by brodyd** [comment]
I've had this problem before and so now I always check with npm pack.  That passed - I cannot figure out why the lib gets missed out sometimes.  I have published a new 3.0.3 version and that is correctly packaged.

Thanks for letting me know.  Sorry it gave you a problem.  It is fixed now (in 3.0.3)
