### ISSUE TITLE
Regex pattern matching not working

### ISSUE THREAD

**Issue by gauravve** [atlantishealthcare/swagger-model-validator#104]
Trying to validate using the following model
```
"user": {
            "title": "User",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "pNumber": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 30,
                    "pattern":"[A-Za-z0-9-]*"
                },
                "org": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 30,
                    "pattern":"[A-Za-z0-9-]*"
                },
                "enabled": {
                    "type": "boolean"
                },
                "userRoles": {
                    "type": "array",
                    "uniqueItems": true,
                    "minItems": 1,
                    "maxItems": 7,
                    "items": {
                        "type": "string",
                        "enum": [
                            "admin",
                            "consumer"
                        ]
                    }
                }
            },
            "required": [
                "pNumber",
                "org"
            ],
}
```

The following should not validate 

```
{
    "pNumber": p!@#$!@#,
    "org": "!@#$!@#$",
    "enabled": true,
    "userRoles": ["orgadmin.prod",
      "admin",
      "consumer"
    ]
  };
```

but validates successfully.

**Comment by brodyd** [comment]
Running your Reg Exp on a Checker I get a total of 9 matches.  Without the * character the pattern match fails as expected.  I'm putting this down as a pattern issue and not a functionality issue.

**Comment by brodyd** [comment]
Internal the pattern is checked using the RegExp function in Javascript with asimple test against the value.

using the checker at regex101.com it looks like you might want to use the pattern ^[A-Za-z0-9-]+$ instead.

**Comment by gauravve** [comment]
I will test today and let you know. Thanks for your help.

**Comment by gauravve** [comment]
Its fixed. Thanks very much for your help.

**Comment by thetumper** [comment]
Similar problem:

Pattern:
^[A-Z]{2}

Data:
W3

The validator is not flagging it as invalid.  Regex101.com does ("Your regular expression does not match the subject string.")

**Comment by brodyd** [comment]
I'd prefer you to raise a new issue @thetumper but before you do please check your settings because I've run a test and the validator will reject W3 with your pattern.  

The validator uses the default regular expression handler for Javascript and isn't doing anything special.  Please not that AA1 will pass as will anything that starts with two capitals.

Add a $ to limit it to two characters '^[A-Z]{2}$' for example.

**Comment by thetumper** [comment]
Thanks.  That fixed an issue with length of the allowed value.  But, it appears the validator still misses invalid values against patterns when the property having the pattern is referenced within a oneOf or anyOf.    I'll open a new issue with more details.
