### ISSUE TITLE
Stack error when validating extra parameters

### ISSUE THREAD

**Issue by guillemdc** [atlantishealthcare/swagger-model-validator#108]
Sometimes when validating, if I am checking that there are no extra values not inidicated in the swagger file, the validator cracks. It seems it might be entering a never ending loop and consuming too much memory at some point. It happens in both NodeJS running on a Ubuntu Server and Google Chrome running on a Windows laptop.

This code:
```
var val = new Validator(swagger);
console.log(val.swagger.validateModel(
    'TicketDetailType',
    JSON.parse('{"id":"20190207111127403175","href":"/ticketing/v2/tick ets/20190207111127403175","customerId":"0000000000000","description":"Problems T EST444","creationDate":"2019-02-07T11:11:28.131-06:00","status":"new","severity" :"moderate","relatedParty":[{"role":"user","id":"5537684787","href":"URL"}],"rel atedObject":[{"href":"unavailable"}],"type":" "}'),
    false,
    true));
})
```

Triggers this error:
```
{readyState: 1, setRequestHeader: ƒ, getAllResponseHeaders: ƒ, getResponseHeader: ƒ, overrideMimeType: ƒ, …}
modelValidator.js:785 Uncaught RangeError: Maximum call stack size exceeded
    at merge (modelValidator.js:785)
    at merge (modelValidator.js:812)
    at merge (modelValidator.js:812)
    at getRefedModel (modelValidator.js:868)
    at getRefedModel (modelValidator.js:881)
    at getRefedModel (modelValidator.js:881)
    at getRefedModel (modelValidator.js:881)
    at getRefedModel (modelValidator.js:881)
    at getRefedModel (modelValidator.js:881)
    at getRefedModel (modelValidator.js:881)
```
The error does not occur when the calling the function without the two last boolean parameters.

The swagger file is attached in case anybody wants to reproduce it. It is in txt format as json files cannot be attached here.

[ticketManagement_v2.4.0.txt](https://github.com/atlantishealthcare/swagger-model-validator/files/2844484/ticketManagement_v2.4.0.txt)

**Comment by brodyd** [comment]
This appears to be caused by looping references.  You have a CategoryTreeType that contains a CategoryTreeType and this causes an infinite loop when dereferencing while checking for Extra Properties.

**Comment by brodyd** [comment]
I have limited the dereferencing to one layer deep which will resolve this issue while still allowing the detection of extra properties.
