### ISSUE TITLE
Validating an Object type

### ISSUE THREAD

**Issue by javatony** [atlantishealthcare/swagger-model-validator#111]
When validating a POST req body where I have a TestModel object that contains properties id and testObject. testObject is defined as expecting to be an object type, but if a different type is provided the error returns `Unable to validate a model with a type: string, expected: object` is thrown. You can imagine that if the TestModel was more complicated and contained multiple object properties that this is not entirely clear as to which property is of invalid type.

Would love to see that an object also gets validated similar to how an array is and includes the name  and explicitly says 'testObject is not an object. An Object is expected' to be consistent.

Array example where improper type is provided: 
'testArray is not an array. An array is expected.'

Below I have the req and the model definition. Is it that I am not properly defining the model or can we improve validateObject to explicitly check that the value is typeOf object before continuing?

Happy to submit a PR for review. Thanks in advance!

Req Body:
`{
	"id": 1,
	"testObject": ""
}`

Model Definition:
```javascript
"TestModel": {
    "type": "object",
        "properties": {
            "id": {
                "type": "string",
                "description": "ID"
                },
            "testObject": {
                "type": "object",
                "properties": {
                    "testObjectProperty": {
                        "type": "string",
                        "description": "testObjectProperty Description"
                    }
                },
                "description": "Testing Example"
            }
        }
}
```

**Comment by brodyd** [comment]
The problem here is that when we validate objects we may not be aware of the property name.

**Comment by brodyd** [comment]
We can improve our object validation by checking for its objectosity before we pass it back to the validation function it is currently checked in.
