### ISSUE TITLE
Model validation passes if the property is type of array with the ref

### ISSUE THREAD

**Issue by sgajavada** [atlantishealthcare/swagger-model-validator#21]
The line 
https://github.com/atlantishealthcare/swagger-model-validator/blob/master/lib/modelValidator.js#L321

var errors = validate(value, model.properties, models);

should be

var errors = validate(value, model, models);

**Comment by brodyd** [comment]
Thanks for that.  I'll push this out as soon as I track down what is causing #20 (Or next Monday)

**Comment by sgajavada** [comment]
Thanks for the quick fix.  Are you releasing a new version of the node module with the fix? https://www.npmjs.com/package/swagger-model-validator
