### ISSUE TITLE
Does not resolve $ref correctly.

### ISSUE THREAD

**Issue by illuxio** [atlantishealthcare/swagger-model-validator#36]
The `$ref` property can contain `#/definitions/cat`, which is not mapped to `model.definitions.cat`.

**Comment by brodyd** [comment]
It appears that the validator does not support the newer Swagger 2.0 definition format

**Comment by brodyd** [comment]
It looks likely that the Swagger-node-express implementation of models has changed appreciably.  We'll need to review its changes as before we can update this.  I've made a naive change in the Swagger2.0 branch that might fix it but I have no Swagger 2.0 to it out on.
