### ISSUE TITLE
support sub model by checking the discriminator field

### ISSUE THREAD

**Issue by jchip** [atlantishealthcare/swagger-model-validator#43]
Swagger 2.0 supports polymorphic models with the discriminator.  Can a check for that be added?

It'd just be a few lines add to here https://github.com/atlantishealthcare/swagger-model-validator/blob/master/lib/modelValidator.js#L29
```js
            var subModelName = model.discriminator && obj[model.discriminator];
            if (subModelName && models[subModelName]) {
                model = models[subModelName];
            }
```

**Comment by brodyd** [comment]
Added code to check the model discriminator as above.  Added test to check function.

**Comment by brodyd** [comment]
I'll push this out now as a patch but it will be rolled up into 2.1 as well.

**Comment by brodyd** [comment]
Thanks for you suggestion @jchip

**Comment by isadovskiy** [comment]
Looks like it works for for top-level model and does not check discriminator in sub-models.

It also won't work on direct `validate()` method call (since discriminator logic is just added into `validateModel` method...)
````
var validation = validator.validate(object, swaggerModel, swaggerModels, allowBlankTarget, disallowExtraProperties);
````
So this issue could not be considered as resolved.
