### ISSUE TITLE
Additional properties not allowed errors when used with swagger-tools

### ISSUE THREAD

**Issue by mattoshry** [atlantishealthcare/swagger-model-validator#51]
We have an application that uses swagger-model-validator@2.0.4 in conjunction with swagger-tools@0.9.10 [1] and a swagger 2.0 schema. After applying custom validation to a model, swagger-tools middleware produces an instance of the following error per model property. (Substitute {definitionName} and {propertyName} with the name of a definition and property within that definition.)

  #/definitions/{definitionName}/properties/{propertyName}: Additional properties not allowed: validatedType

The source of the trouble is around [2] which adorns model properties with a custom `validatedType` property. According to [3] custom properties must be prefixed with `x-`.

[1] https://www.npmjs.com/package/swagger-tools
[2] https://github.com/atlantishealthcare/swagger-model-validator/blob/fdc6a4ba55ef86cc45b18778196b833152f90175/lib/modelValidator.js#L431
[3] https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

**Comment by brodyd** [comment]
I'll modify the property to x-validatedType.
