### ISSUE TITLE
Validation of a FHIR resource

### ISSUE THREAD

**Issue by mdigirolami** [atlantishealthcare/swagger-model-validator#54]
I'm trying to validate a JSON string respect a FHIR resource, specifically for a FHIR Questionnaire resource (https://www.hl7.org/fhir/questionnaire.html).
Attachments to the issue you can find:
- used swagger definition (obtained with tool [fhir-swagger](https://github.com/bobby-brennan/fhir-swagger) with some minor changes);
- JSON string to validate respect given swagger (it is an official FHIR example: https://www.hl7.org/fhir/questionnaire-example-f201-lifelines.json)

Runing this script:
`var Validator = require('swagger-model-validator');
var swagger = require('./fhir_swagger.json');
var validator = new Validator(swagger);
var objToValidate = require('./Questionnaire-example-f201-lifelines.json');
var validation = swagger.validateModel("Questionnaire", objToValidate, true, true);
console.log(validation);`

I obtain this output:
`{ valid: false,
  errorCount: 1,
  errors: [ [Error: contained is a required field] ],
  GetErrorMessages: [Function],
  GetFormattedErrors: [Function] }`

I don't understand this error because it seems to me that the "contained" field is not mandatory (in line 17209 of swagger definition you can see the definition of "contained" field provided for the Questionnaire object). I've also tried to delete at all the definition of "contained" field (lines 17209-17290) but I have the same error, I' think I'm using the swagger-model-validator tool in a wrong way, can you help me please?

Marco

[fhir_swagger.txt](https://github.com/atlantishealthcare/swagger-model-validator/files/328152/fhir_swagger.txt)

[Questionnaire-example-f201-lifelines.txt](https://github.com/atlantishealthcare/swagger-model-validator/files/328153/Questionnaire-example-f201-lifelines.txt)

**Comment by brodyd** [comment]
Line 17456 of the swagger definition seems to show that contained is a required field.  You would have to remove it from the required array (starting on 17452) for it to be non-required.  Removing it as a property will not remove it from the required list.

**Comment by brodyd** [comment]
It looks like the definition does not match the example.  Removing 'contained' from the required array (line 17456) should make the example match the definition properly.

**Comment by mdigirolami** [comment]
You are right. Thanks.
