### ISSUE TITLE
type's required array property ignored

### ISSUE THREAD

**Issue by bushuyev** [atlantishealthcare/swagger-model-validator#57]
Hi

I have type def:

```
"AmountRange": {
      "type": "object",
      "required": [
        "ccyCode",
        "fromAmount",
        "toAmount"
      ],
      "properties": {
        "fromAmount": {
          "type": "number"
        },
        "toAmount": {
          "type": "number"
        },
        "ccyCode": {
          "type": "string",
          "pattern": "[A-Z]{3}"
        }
      }
    },
```
but validator accepts 

"amountRange":{"fromAmount":10,"toAmount":100}}

whithout any errors. Bug?

**Comment by brodyd** [comment]
It might be that you are supplying "amountRange" but have defined it as "AmountRange" so it will be passing by default (any undefined values are valid unless you have set a specific flag to cause unknown values to fail).

**Comment by bushuyev** [comment]
sorry, forgotten to add type itself:
"MyType": {
      "type": "object",
      "properties": {
         "amountRange": {
           "$ref": "#\/definitions\/AmountRange"
         }
      }
}

so, no, case should be ok.

**Comment by brodyd** [comment]
I'm note sure you ref is correct.  Shouldn't it be "#/definitions/AmountRange" and **not** "#\/definitions\/AmountRange".  To my mind that probably means that the reference is to nothing and by default everything will pass.  I'll try a test and see what happens.

**Comment by brodyd** [comment]
I think it is how you have quoted the name parts of the json.

Try taking the quotes off all of the name parts.

MyType: {
                    type: "object",
                    properties: {
                        amountRange: {
                            $ref: "#\/definitions\/AmountRange"
                        }
                    }
                },
            AmountRange: {
                type: "object",
                required: [
                    "ccyCode",
                    "fromAmount",
                    "toAmount"
                ],
                properties: {
                    fromAmount: {
                        type: "number"
                    },
                    toAmount: {
                        type: "number"
                    },
                    ccyCode: {
                        type: "string",
                        pattern: "[A-Z]{3}"
                    }
                }

**Comment by brodyd** [comment]
Now that I have run the tests - I do not appear to be able to replicate the issue.  It works correctly both ways.

Do you have any more information I can use to track this down?

**Comment by brodyd** [comment]
Here is the error I've added

```
hasRefWithExcapedDefinitionPrefixTest3: function(test) {
        var data = {
            "amountRange":{"fromAmount":10,"toAmount":100}
        };

        var models = {
            "MyType": {
                "type": "object",
                "properties": {
                    "amountRange": {
                        "$ref": "#\/definitions\/AmountRange"
                    }
                }
            },
            "AmountRange": {
                "type": "object",
                "required": [
                    "ccyCode",
                    "fromAmount",
                    "toAmount"
                ],
                "properties": {
                    "fromAmount": {
                        "type": "number"
                    },
                    "toAmount": {
                        "type": "number"
                    },
                    "ccyCode": {
                        "type": "string",
                        "pattern": "[A-Z]{3}"
                    }
                }
            }
        };

        var errors = validator.validate(data, models["MyType"], models);

        test.expect(2);
        test.ok(errors.errors[0].message == 'ccyCode is a required field');
        test.ok(!errors.valid);
        test.done();
    }
```
Note that errors.valid is not true - meaning that there is an error. In this case 'ccyCode is a required field' as expected.

Sorry I can't resolve this for you with the information I have @bushuyev. Good luck.
