### ISSUE TITLE
x-nullable support?

### ISSUE THREAD

**Issue by MitchellBurton** [atlantishealthcare/swagger-model-validator#67]
As per the conversation here: #63 

The swagger spec doesn't support null as a type value. So when testing for an empty object the distinction between {} and { prop: null } doesn't make any sense.

I propose that swagger-model-validator supports x-nullable on properties. See _add "null value support" in spec?_ https://github.com/OAI/OpenAPI-Specification/issues/229

This would allow {} and { prop: null } to validate differently, but I am currently unsure what other effects this would have on validation logic.

**Comment by brodyd** [comment]
Are we trying to tell us which properties are unexpectedly null so we can easily track them down?

That is already really handled by the required parameter.  Adding support for the x-isnullable or x-nullable could make sense but I'm not sure of the use case. Any removal of a value should usually be done under a DELETE and could be handled without this.
