### ISSUE TITLE
"allOf" support

### ISSUE THREAD

**Issue by brodyd** [atlantishealthcare/swagger-model-validator#71]
Should we support the allOf keyword in the Swagger 2.0 (now OpenAPI) specification?

**Comment by brodyd** [comment]
+1

**Comment by brodyd** [comment]
I've just tried adding a poll but it created this extra issue - leave your vote in either issue or make a pull request...

**Comment by hugoduraes** [comment]
Yes, this would be great! I think @jjcross already has this implemented on his fork. Check it here please:
https://github.com/jjcross/swagger-model-validator/commit/f5d80a141133c6db6e9b1a8d6b810d1bb00f0b4f

**Comment by isadovskiy** [comment]
Implemented `getMergedModel` works incorrectly. It breaks the original schema. it duplicates and injects pieces of schema from one place into another. Here is an example: http://take.ms/bFeun It compares schema object before validateModel execution and after it. As you can see, it injected piece from another place. Problem occurred after updating to new version, which supports allOf
