### ISSUE TITLE
Implement real 'discriminator'-Support

### ISSUE THREAD

**Issue by YStrauch** [atlantishealthcare/swagger-model-validator#76]
Hello,
[issue 43](https://github.com/atlantishealthcare/swagger-model-validator/issues/43) is not resolved yet. As stated in the last comment, the implementation lacks support for sub models (which is a very big deal breaker for me), and it was only added to validateModel(), not to validate().

**Comment by brodyd** [comment]
We have moved the discriminator detection and handling into the validate area so it is performed for all models and submodels.

We have updated the tests and included handling of the allowExtraProperties errors so they do not affect the discriminator field.

Hopefully this will support your @isadovskiy issue.
