### ISSUE TITLE
"Unable to validate an undefined value" raised on a not required property

### ISSUE THREAD

**Issue by bushuyev** [atlantishealthcare/swagger-model-validator#81]
I have a swagger def like

```
    "MyType": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
           "type": "string",
        },
        "some": {
          "$ref": "#/definitions/Something"
        }
  }
```
validation of an object 
```
{
 name: 'zzz'
 some: null
}
```

fails with "Unable to validate an undefined value: some'"

can it be a warning? The null value is not dissalowed by swagger def for the 'some' field, isn't it?

**Comment by bushuyev** [comment]
and same with arrays.

**Comment by brodyd** [comment]
Nullable fields are not really allowed by the swagger definition.  You can leave a field out and if it is not required it will pass validation but you can only have a nullable field if you include 'x-nullable': true in the definition.

```javascript
{
    required: [ 'id', 'count' ],
    properties: {
        id: {
            type: 'number',
            description: 'The object id'
        },
        count: {
            type: 'number',
            description: 'A number',
            'x-nullable': true
        }
    }
}
```
will allow validation of the object
```javascript
{
    id: 1,
    count: null
}

**Comment by brodyd** [comment]
I have added a unit test of your exact sample (fixed the object) and it does pass validation.  Can you send me a complete definition and a complete data object that fails.  The smallest failing sample would be best and then I can confirm if it is behaving as expected or not.

**Comment by bushuyev** [comment]
Thank you for clarifying! The object and model in your test perfectly replecate the problem so I have nothing new to send and setting 'x-nullable': true fixes it.
