### ISSUE TITLE
Support for Open API 3.0

### ISSUE THREAD

**Issue by brodyd** [atlantishealthcare/swagger-model-validator#82]
With the recent release of Open API 3.0 will we add support for that level.  We currently support 1.2 and 2.0.

3.0 seems to have some changes in locations but most of the parts seem the same.... I feel it would be quite a refactoring though.

Does anyone want to see a version for 3.0?

**Comment by Bomret** [comment]
Of course! Would be nice as there aren't that much Swagger validation libs on npm AFAIK.

**Comment by KshitijShah** [comment]
How  soon support for 3.0 will be available

**Comment by brodyd** [comment]
Can anyone send me some Open Api 3.0 specs and sample objects so I can get started on this?
