### ISSUE TITLE
v2.2.2 seems to be missing lib folder after installation

### ISSUE THREAD

**Issue by abhiche** [atlantishealthcare/swagger-model-validator#89]
Hi @brodyd,
Thanks for your quick action on the PR [88](https://github.com/atlantishealthcare/swagger-model-validator/pull/88).
But after installing v2.2.2, I am receiving an error as below:

```
Error: Cannot find module './lib/modelValidator.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/abhi/projects/swagger-validation-test/node_modules/swagger-model-validator/index.js:4:18)
```

From my finding, this module is missing lib folder after installation.

**Comment by cvbuelow** [comment]
I'm seeing the same. Please fix this asap.

**Comment by mukundgoel** [comment]
Anybody looking into this? Looks like a case of a bad npm publish.

**Comment by ajoshi0** [comment]
@brodyd can you please jump on this

**Comment by brodyd** [comment]
I'm on it now

**Comment by brodyd** [comment]
I'm not sure why the lib folder was not packaged.  Publish just stopped picking it up.  I've added all of the required files to the package now so they should be correctly handled.  I've done a test publish and it seems okay now
