### ISSUE TITLE
Doesn't validate list of required fields

### ISSUE THREAD

**Issue by jeweua** [atlantishealthcare/swagger-model-validator#93]
Given followin sample model
```
    "Entity": {
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
```
and json object
```
const testData = {
  id: '1'
}
```
When I do 
swagger.validateModel('Entity', json )

I receive `{ valid: true, errorCount: 0 }`
But why does it not validate that `name` field is required by the model but is not present in testData?

**Comment by brodyd** [comment]
'name' is not defined as required.  You need to change your model to be more like:
```
"Entity": {
      "required": [ id, name ]
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
```
Required properties are identified in an array of strings in the required property.
